/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.42
 * Generated at: 2018-01-19 13:32:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Amministratore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/AsideAmm.jsp", Long.valueOf(1516368723871L));
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1516103139473L));
    _jspx_dependants.put("/HeaderAmm.jsp", Long.valueOf(1513035816796L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Content-Language\" content=\"it\">\r\n");
      out.write("<meta name=”description” content=”Drive-in.com–Negozio_di_scarpe_online”>\r\n");
      out.write("<meta name=\"author\" content=\"Giulio Di Maria, Matteo Volpe\">\r\n");
      out.write("<meta name=\"keywords\" content=\"shoes, Drive-in, italian-style\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, intial-sclae=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/benvenuto.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"cambio.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"addProdotto.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"clearTable.js\"></script>\r\n");
      out.write("<title>Amministratore</title>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar valid =\r\n");
      out.write("\t[];//variabile per sapere il totale degli elementi realmente caricati precedentemente\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"Imm/bianco.jpg\">\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload = (cambio(\"Tutto\", \"T\", null, 1))\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Language\" content=\"it\">\r\n");
      out.write("\t\t<meta name=”description” content=”Drive-in.com–Negozio_di_scarpe_online”>\r\n");
      out.write("\t\t<meta name=\"author\" content=\"Giulio Di Maria, Matteo Volpe, Angela Ursi\">\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"shoes, Drive-in, italian-style\"> \r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, intial-sclae=1.0\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"CSS/Ammheaders.css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"aggiungiprodotti.js\"></script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"ricercami.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body background=\"Imm/bianco.jpg\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"logo\"><a href=\"Amministratore.jsp\"><img id=\"logo\" src=\"Imm/Logo.png\" alt=\"Logo\"></a></th>\r\n");
      out.write("\t\t\t\t\t<th class=\"ricerca\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<h3> Sito ufficiale di Drive-In</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <input onsubmit=\"cambio(null,null,ricerca_oggetti.value,0)\" type=\"text\" id=\"ricercabar\" name=\"ricerca_oggetti\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <input onclick=\"cambio(null,null,ricerca_oggetti.value,0)\" type=\"image\" id=\"lente\" src=\"Imm/Lente.png\" alt=\"lente per la ricerca\"> -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"accesso\">\r\n");
      out.write("\t\t\t\t\t\t<p>Benvenuto Amministratore ");
      out.print(session.getAttribute("user") );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t<!-- da linkare al carello -->\r\n");
      out.write("\t\t\t\t\t<th class=\"carts\">\r\n");
      out.write("\t\t\t\t\t\t<p id =\"testo\">Operazioni</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Inserisci.jsp\" title=\"Aggiungi\"><img  alt=\"Cart\" src=\"Imm/verde.png\"></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Logout\" title=\"Logout\"><img  alt=\"Cart\" src=\"Imm/Bye.png\"></a>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<aside>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<div id=\"showing\">\r\n");
      out.write("\t\t<aside>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Language\" content=\"it\">\r\n");
      out.write("\t<meta name=”description” content=”Drive-in.com–Negozio_di_scarpe_online”>\r\n");
      out.write("\t<meta name=\"author\" content=\"Giulio Di Maria, Matteo Volpe\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"shoes, Drive-in, italian-style\"> \r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"CSS/Aside.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"cambio.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"addProdotto.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"SelezioneVeloceAmm.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"Inizialmente.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"clearTable.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar flag=true;\r\n");
      out.write("\twindow.onresize = SelezioneVeloceAmm();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<title>Aside</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"Imm/bianco.jpg\">\r\n");
      out.write("\t<div id=\"selezione\">\r\n");
      out.write("\t\t<h3>Selezione Rapida</h3>\r\n");
      out.write("\t\t<p id=\"JustForMe\"> </p>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"Uomo\"><button onclick=\"cambio('Tutto','M','null',1)\">Uomo</button>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li id=\"scarpeu\"><button onclick=\"cambio('Scarpa','M','null',1)\"> Scarpe </button></li>\t\r\n");
      out.write("\t\t\t\t\t<li id=\"accessoriu\" ><button onclick=\"cambio('Borsa','M','null',1)\">Borse </button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li class=\"Donna\"><button onclick=\"cambio('Tutto','D','null',1)\">Donna</button>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li id=\"scarped\"> <button onclick=\"cambio('Scarpa','D','null',1)\">Scarpe</button></li>\r\n");
      out.write("\t\t\t\t\t<li id=\"accessorid\"><button onclick=\"cambio('Borsa','D','null',1)\">Borse</button></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Language\" content=\"it\">\r\n");
      out.write("\t<meta name=”description” content=”Drive-in.com–Negozio_di_scarpe_online”>\r\n");
      out.write("\t<meta name=\"author\" content=\"Giulio Di Maria, Matteo Volpe\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"shoes, Drive-in, italian-style\"> \r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"bianco.jpg\">\r\n");
      out.write("\t<h2>Contatti</h2>\r\n");
      out.write("\t<address> \r\n");
      out.write("\t\tGruppo composto da : <b>Giulio Di Maria (05121 03518)</b>, <b>Matteo Volpe (05121 03656)</b>. </b> <br>\r\n");
      out.write("\t\tPer info si prega di contattarci sulla rispettive e-mail unisa. \r\n");
      out.write("\t</address>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
