/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.42
 * Generated at: 2018-01-18 02:01:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Inserisci_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Inserisci</title>\r\n");
      out.write("<script>\r\n");
      out.write("function prodotto(val)\r\n");
      out.write("{\r\n");
      out.write("\tvar txt=\"\";\r\n");
      out.write("\tvar marc=\"\";\r\n");
      out.write("\tvar prodotto = val; // mi vado a prendere il valore che voglio inserire\r\n");
      out.write("\t\r\n");
      out.write("\tif(prodotto == 'Scarpa')\r\n");
      out.write("\t{\r\n");
      out.write("\t\r\n");
      out.write("\tvar taglia=[\r\n");
      out.write("\t           \"33\",\r\n");
      out.write("\t           \"34\",\r\n");
      out.write("\t           \"35\",\r\n");
      out.write("\t           \"36\",\r\n");
      out.write("\t           \"37\",\r\n");
      out.write("\t           \"38\",\r\n");
      out.write("\t           \"39\",\r\n");
      out.write("\t           \"40\",\r\n");
      out.write("\t           \"41\",\r\n");
      out.write("\t           \"42\",\r\n");
      out.write("\t           \"43\",\r\n");
      out.write("\t           \"44\",\r\n");
      out.write("\t           \"45\",\r\n");
      out.write("\t           \"46\"\r\n");
      out.write("\t          ];\r\n");
      out.write("\t\t\ttxt +=\"<select>\"\r\n");
      out.write("\t\t\tfor(var i=0; i<taglia.length; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t txt += \"<option>\" + taglia[i];\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttxt+=\"</select>\"\r\n");
      out.write("\t\t\tdocument.getElementById(\"taglia\").innerHTML= txt;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("// \t\t\tvar marca=[\r\n");
      out.write("// \t\t\t           \"Addidas\",\r\n");
      out.write("// \t\t\t           \"Puma\",\r\n");
      out.write("// \t\t\t           \"Nike\",\r\n");
      out.write("// \t\t\t           \"Alcoot\"\r\n");
      out.write("// \t\t\t           ];\r\n");
      out.write("\t\t\r\n");
      out.write("// \t\t\t\tmarc +=\"<select>\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("// \t\t\tfor(var j=0; j<marca.length; j++)\r\n");
      out.write("// \t\t\t\t{\r\n");
      out.write("// \t\t\t\t\tmarc += \"<option>\" + marca[j];\r\n");
      out.write("// \t\t\t\t}\r\n");
      out.write("// \t\t\t\tmarc+=\"</select>\"\r\n");
      out.write("// \t\t\t\tdocument.getElementById(\"Nome\").innerHTML= marc;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(prodotto == 'Borsa')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar misura=[\r\n");
      out.write("\t\t\t            \"S\",\r\n");
      out.write("\t\t\t            \"M\",\r\n");
      out.write("\t\t\t            \"L\"\r\n");
      out.write("\t\t\t            ];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttxt +=\"<select>\"\r\n");
      out.write("\t\t\t\tfor(var i=0; i<misura.length; i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t txt += \"<option>\" + misura[i];\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\ttxt+=\"</select>\"\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"taglia\").innerHTML= txt;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("// \t\t\t\tvar marca=[\r\n");
      out.write("// \t\t\t\t           \"D&G\",\r\n");
      out.write("// \t\t\t\t           \"Pandora\",\r\n");
      out.write("// \t\t\t\t           \"Gucci\",\r\n");
      out.write("// \t\t\t\t           \"Prada\"\r\n");
      out.write("// \t\t\t\t           ];\r\n");
      out.write("\t\t\t\r\n");
      out.write("// \t\t\t\t\tmarc +=\"<select>\"\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("// \t\t\t\tfor(var j=0; j<marca.length; j++)\r\n");
      out.write("// \t\t\t\t\t{\r\n");
      out.write("// \t\t\t\t\t\tmarc += \"<option>\" + marca[j];\r\n");
      out.write("// \t\t\t\t\t}\r\n");
      out.write("// \t\t\t\t\tmarc+=\"</select>\"\r\n");
      out.write("// \t\t\t\t\tdocument.getElementById(\"Nome\").innerHTML= marc;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\treturn prodotto;\r\n");
      out.write("}\r\n");
      out.write("function sesso (val)\r\n");
      out.write("{\r\n");
      out.write("\tvar x = val;\r\n");
      out.write("\t//alert(\"fa0\"+ x);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function tag(taglia)\r\n");
      out.write("{\r\n");
      out.write("\tvar x = taglia\r\n");
      out.write("\t//alert(\"taglia selezionata\"+ x); \r\n");
      out.write("\treturn x;\r\n");
      out.write("}\r\n");
      out.write("function imm(i)\r\n");
      out.write("{\r\n");
      out.write("\tvar z= i;\r\n");
      out.write("\t//alert(\"sto selezionando\"+ z);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function Aggiungi ()\r\n");
      out.write("{\r\n");
      out.write("\tvar file = document.getElementById(\"photo\").value;\r\n");
      out.write("\tfile = file.substring(file.lastIndexOf('\\\\')+1);\r\n");
      out.write("\tvar tipo = document.getElementById(\"selezione\").value;\r\n");
      out.write("\tvar sess = document.getElementById(\"sesso\").value;\r\n");
      out.write("\t\r\n");
      out.write("\tvar col= document.getElementById(\"colore\").value;\r\n");
      out.write("\t// si \r\n");
      out.write("\t\r\n");
      out.write("\tvar N_ele= document.getElementById(\"numeroE\").value;\r\n");
      out.write("\r\n");
      out.write("\tvar codice = document.getElementById(\"codice\").value;\r\n");
      out.write("\t// si\r\n");
      out.write("\t\r\n");
      out.write("\tvar prezzo = document.getElementById(\"Prezzo\").value;\r\n");
      out.write("\t//alert(\"selezionato il prezzo\"+ prezzo);\r\n");
      out.write("\t\r\n");
      out.write("\tvar taglia= document.getElementById(\"taglia\").value;\r\n");
      out.write("\t//si\r\n");
      out.write("\tvar n= document.getElementById(\"Nome\").value;\r\n");
      out.write("\r\n");
      out.write("\t//si\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar xhttp = new XMLHttpRequest();\r\n");
      out.write("\txhttp.onreadystatetchange = function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(this.readyState == 4 && this.status == 200 )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//alert (\"sto ricevendo la seguente risposta \"+ this.responseText); // ricevo un oggetto JSON\r\n");
      out.write("\t\t\tobj = JSON.parse(this.responseText);\r\n");
      out.write("\t\t\t//alert(\"Ecco la risposta\"+ obj);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\tvar query=\"?tipo=\"+tipo+\"&n=\"+n+\"&sesso=\"+sess+\"&col=\"+col+\"&nE=\"+ N_ele+\"&cod=\"+codice+\"&prez=\"+prezzo+\"&tag=\"+taglia+\"&photo=\"+file;\r\n");
      out.write("\txhttp.open(\"GET\",\"InserisciAmministratore\"+query,true);\r\n");
      out.write("\txhttp.send();\r\n");
      out.write("\t//alert(\"sto inviando la seguente query\"+ query);\r\n");
      out.write("\t// ora il problema sta nel prendere i valori degli oggetti che ho costruito dinamicamente attravreso jsvascript\r\n");
      out.write("\talert(\" Ho aggiunto il prodotto : tipo=\"+tipo+\" nome =\"+n+\" sesso=\"+sess+\" col=\"+col+\" con disp=\"+ N_ele+\" codice=\"+codice+\" prez=\"+prezzo+\" tag=\"+taglia);\r\n");
      out.write("\t//\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body background=\"Imm/bianco.jpg\">\r\n");
      out.write("<form action=\"InserisciAmministratore\">\r\n");
      out.write("<a id=\"ritorno\" href=\"Amministratore.jsp\"><img title=\"Home amministratore\" src=\"Imm/FRECCIA.png\"></a>\r\n");
      out.write("<br><br>\r\n");
      out.write("Prodotto\r\n");
      out.write("<select id=\"selezione\" >\r\n");
      out.write("<option id=\"prodotto\" value=\"Scarpa\" onClick=\"prodotto(this.value)\"> Scarpa </option>\r\n");
      out.write("<option id=\"accessori\" value=\"Borsa\" onClick=\"prodotto(this.value)\"> Borsa</option>\r\n");
      out.write("</select>\r\n");
      out.write("<p id=\"\">\r\n");
      out.write("\r\n");
      out.write("<label>Sesso</label>\r\n");
      out.write("<select id=\"sesso\">\r\n");
      out.write("<option id=\"Uomo\" value =\"M\" onClick=\"sesso(this.value)\">MASCHILE</option>\r\n");
      out.write("<option id=\"Donna\" value=\"D\" onClick=\"sesso(this.value)\" >FEMMINILE </option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("Colore\r\n");
      out.write("<input id=\"colore\" type=\"color\">\r\n");
      out.write("\r\n");
      out.write("#Elementi\r\n");
      out.write("<input id=\"numeroE\" type=\"text\">\r\n");
      out.write("\r\n");
      out.write("Taglia\r\n");
      out.write("<select id=\"taglia\" onchange=\"tag(this.value)\">\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("Codice\r\n");
      out.write("<input id=\"codice\" type=\"text\">\r\n");
      out.write("Prezzo\r\n");
      out.write("<input id=\"Prezzo\" type=\"text\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("Nome\r\n");
      out.write("<input id=\"Nome\" type=\"text\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("Photo:\r\n");
      out.write("<input type=\"File\" name=\"photo\" id=\"photo\" >\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" value=\"Aggiungi\" onclick=\"Aggiungi()\"> \r\n");
      out.write("\r\n");
      out.write("<!-- ora devo far in modo di far apparire la foto ( in stringhe) dell'oggetto che sto selezionando -->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
